# Generated by Django 2.1.5 on 2019-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20190211_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
